// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG-lLs2_TuHq24rnH0LASUq5Jitw06Q7w',
    appId: '1:435296988529:web:2815fb138e9a7980251ad0',
    messagingSenderId: '435296988529',
    projectId: 'to-do-list-cc13a',
    authDomain: 'to-do-list-cc13a.firebaseapp.com',
    storageBucket: 'to-do-list-cc13a.appspot.com',
    measurementId: 'G-EYX71XMP16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-tW4CIkXP6jA4Q4Vroo4o8JxPFI28cNs',
    appId: '1:435296988529:android:4e51a47f666b74b1251ad0',
    messagingSenderId: '435296988529',
    projectId: 'to-do-list-cc13a',
    storageBucket: 'to-do-list-cc13a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhKxhdyjgIFlt-LXP8E4rrKEkwH_8didE',
    appId: '1:435296988529:ios:35bdb9ef1aa36c03251ad0',
    messagingSenderId: '435296988529',
    projectId: 'to-do-list-cc13a',
    storageBucket: 'to-do-list-cc13a.appspot.com',
    iosBundleId: 'com.example.todolistFirebase',
  );
}
